title:       Yash Raj Singh
subtitle:    Developer, Designer & Hacker
description: Yash Raj Singh is a developer & designer from India.

author:    Yash Raj Singh
email: 	   mail.yashrajsingh@gmail.com
github:    https://github.com/yashrajsingh/
twitter:   https://twitter.com/iamyashrajsingh
facebook:  https://facebook.com/yashrajsingh.net
google:    https://google.com/+YashRajSingh
linkedin:  https://in.linkedin.com/in/yashrajsingh/

exclude:     [_deploy, Gemfile, Gemfile.lock, Rakefile, README.md, temp.txt]

source:      _source
destination: _deploy
markdown:  rdiscount
permalink: /:title.html
gems:
  - jekyll-coffeescript
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      title: "Yash Raj Singh, Developer, Designer"
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog"
      category: shares

sass:
  style:    :compressed
  sass_dir: assets/stylesheets
